version: '3.4'

services:

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - docker-network

  invest-service:
    build:
      context: ../../invest-service
      dockerfile: src/Invest.Services.Api/Dockerfile
    container_name: invest-service
    ports:
      - '5000:80'
    networks:
      - docker-network
    depends_on:
      - redis
    healthcheck:
      test: 'curl -s http://localhost:5000/api/health >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi'
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  docker-network:
    driver: bridge

volumes:
  docker-volume:
    driver: local
